packages:
  - apps/desktop-client
  - apps/server
  - apps/mobile-client
allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  msw: false
minimumReleaseAgeExclude:
  - '@tanstack/devtools@0.13.0'
  - '@tanstack/react-devtools@0.10.9'
  - '@tanstack/react-virtual@3.14.8'
  - '@tanstack/virtual-core@3.17.6'
  - react-dom@19.2.8
  - react@19.2.8
  - shadcn@4.14.0

catalog:
  "@biomejs/biome": ^2.5.5
  tailwindcss: ^4.3.3
  typescript: ^7.0.2
