[package]
name = "hermes-server"
version = "0.1.0"
edition = "2024"

[[bin]]
name ="gen-openapi"
path = "src/bin/gen-openapi.rs"

[[bin]]
name = "hermes-server"
path = "src/main.rs"

[dependencies]
prost = "0.14"
prost-types = "0.14"
urlencoding = "2.1.3"
actix-session = { version = "0.11.0", features = ["cookie-session"]}
actix-csrf-middleware = "0.7"
actix-identity = "0.9.0"
actix = "0.13"
actix-files = "0.6"
actix-web = "4"
actix-ws = "0.4.0"
actix-cors ="0.7"
actix-web-validation = {version = "0.8.0", features = ["validator"]}
actix-ws-broadcaster = "0.12.0"
jsonwebtoken = { version = "11", features = ["aws_lc_rs"] }
ed25519-dalek = { version = "3.0", features = ["pkcs8", "pem"] }
actix-governor = "0.10"
futures-util = "0.3"
sha2 = "0.11"
log = "0.4"
base64 = "0.23"
rand = "0.10"
sqlx = { version = "0.9", features = [ "runtime-tokio", "sqlite","derive", "macros","migrate","bstr", "time","uuid","sqlx-toml"] }
tokio = { version = "1", features = ["time", "rt", "macros"] }
validator = { version = "0.20", features = ["derive", "unic"] }
utoipa = { version = "5.4", features = ["actix_extras","yaml","uuid","time"]}
utoipa-actix-web = "0.1"
log4rs = "1.4"
totp-rs = { version = "5.7", features = ["gen_secret"]}
dotenvy = "0.15.7"
url = "2.5"
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
argon2 = "0.5.3"
uuid = { version = "1", features = ["v7","serde","fast-rng"] }
time = { version = "0.3", features = ["serde","serde-well-known"]}
nanoid = "0.5.0"
reqwest = { version = "0.13", features = ["json"] }

[build-dependencies]
prost-build = "0.14"
oxc = { version = "0.141", features = ["minifier","codegen","mangler","transformer","semantic"] }

[profile.dev.package.sqlx-macros]
opt-level = 3

[profile.release] 
opt-level = "s"  # Optimize for binary size
strip = true  # Remove debug symbols
lto = true  # Enables link to optimizations
panic =  "unwind"  # Strip expensive panic clean-up logic
codegen-units = 1  # Compile crates one after another so the compiler can optimize better
