syntax = "proto3";

package hermes;

message Envelope {
    string messageId = 1;
    int64 timestamp = 2;
    uint32 version = 3;
  
    oneof payload {
        // RTC 1X
        RtcEvent rtc = 10;
        RtcNewCandidate rtcIce = 11;

        // Client -> Server 1XX
        VoiceChannelRequest voiceChannelRequest = 100;
      

        // Server -> Client 2XX
        VoiceChannelUserEvent voiceChannelEvent = 200;
    }
}

// Client -> Server 1XX
message VoiceChannelUserEvent {
    enum VoiceChannelEventType {
        Join = 0;
        Leave = 1;
    }

    string channelId = 1;
    VoiceChannelEventType type = 2;
    string userId = 3;
}

// Server -> Client 2XX
message VoiceChannelRequest {
    string channelId = 1;
    VoiceChannelEventType type = 2;
}

// RTC 1X
message RtcEvent {
    enum RtcMessageType {
        Null = 0;
        Offer = 1;
        Answer = 2;
        PrAnswer = 3;
    }

    RtcMessageType type = 1;
    string target = 2;
    string sdp = 3;
}

message RtcNewCandidate {
    message IceCandidate {
        optional string candidate = 1;
        optional string sdpMid = 2;
        optional int64 sdpMLineIndex = 3;
        optional string usernameFragment = 4;
    }

    string target = 1;
    IceCandidate candidate = 2;
}