syntax = "proto3";

package hermes;

message Envelope {
    string messageId = 1;
    int64 timestamp = 2;
    uint32 version = 3;
  
    oneof payload {
        // RTC 1X
        RtcEvent rtc = 10;
        RtcNewCandidate rtcIce = 11;

        // Client -> Server 1XX
        VoiceChannelRequest voiceChannelRequest =  100;
        bool                presenceEventRequest = 101;
        MessageEventRequest messageEventRequest =  102;
        string              typingEventRequest  =  103;
      

        // Server -> Client 2XX
        VoiceChannelUserEvent voiceChannelEvent = 200;
        PresenceEvent         presenceEvent     = 201;
        TypingEvent           typingEvent       = 202;
        MessageEvent          messageEvent      = 203;
     
    }
}

message TypingEvent {}

message PresenceEvent {

}

message MessageEvent {
    MessageEventType type = 1;
}

message MessageEventRequest {
    string message_id = 1;
    string channel_id = 2;
    MessageEventType type = 3;
}

enum MessageEventType {
    New = 0;
    Edit = 1;
    Delete = 2;
}




// Client -> Server 1XX
enum VoiceChannelEventType {
    Join = 0;
    Leave = 1;
}

message VoiceChannelUserEvent {
 
    string channelId = 1;
    VoiceChannelEventType type = 2;
    string userId = 3;
}

// Server -> Client 2XX
message VoiceChannelRequest {
    string channelId = 1;
    VoiceChannelEventType type = 2;
}

// RTC 1X
message RtcEvent {
    enum RtcMessageType {
        Offer = 0;
        Answer = 1;
        PrAnswer = 2;
        Rollback = 3;
    }

    RtcMessageType type = 1;
    string target = 2;
    string sdp = 3;
}

message RtcNewCandidate {
    message IceCandidate {
        optional string candidate = 1;
        optional string sdpMid = 2;
        optional int64 sdpMLineIndex = 3;
        optional string usernameFragment = 4;
    }

    string target = 1;
    IceCandidate candidate = 2;
}