syntax = "proto3";

package hermes;


message Envelope {
    string messageId = 1;
    int64 timestamp = 2;
    uint32 version = 3;
  
    oneof payload {
        // RTC 1X
        RtcEvent rtc = 10;
        RtcNewCandidate rtcIce = 11;

        // Client -> Server 1XX
        VoiceChannelRequest voiceChannelRequest = 100;
      

        // Server -> Client 2XX
        VoiceChannelUserEvent voiceChannelEvent = 200;
    }
}

enum VoiceChannelEventType {
    Join = 0;
    Leave = 1;
}

// Client -> Server 1XX
message VoiceChannelUserEvent {
    string channelId = 1;
    VoiceChannelEventType type = 2;
    string userId = 3;
}

// Server -> Client 2XX
message VoiceChannelRequest {
    string channelId = 1;
    VoiceChannelEventType type = 2;
}

//#region RTC
enum RtcMessageType {
    Offer = 0;
    Answer = 1;
}

message RtcEvent {
    RtcMessageType type = 1;
    string target = 2;
    string sdp = 3;
}

message RtcNewCandidate {
    string target = 1;
    string candidate = 2;
}
//#endregion