// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v7.35.0
// source: hermes.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "hermes";

/** shared */
export enum PresenceStatus {
  UNSPECIFIED = 0,
  ONLINE = 1,
  IDLE = 2,
  DND = 3,
  INVISIBLE = 4,
  OFFLINE = 5,
  UNRECOGNIZED = -1,
}

export enum VoiceChannelEventType {
  UNSPECIFIED = 0,
  JOIN = 1,
  LEAVE = 2,
  UNRECOGNIZED = -1,
}

export interface Envelope {
  envelopeId: string;
  timestamp: number;
  version: number;
  payload:
    | //
    /** RTC 1X */
    { $case: "rtc"; value: RtcEvent }
    | { $case: "rtcIce"; value: RtcNewCandidate }
    | //
    /** Client -> Server 1XX */
    { $case: "voiceChannelRequest"; value: VoiceChannelRequest }
    | { $case: "presenceEventRequest"; value: PresenceUpdateRequest }
    | { $case: "typingEventRequest"; value: TypingRequest }
    | //
    /** Server -> Client 2XX */
    { $case: "voiceChannelEvent"; value: VoiceChannelUserEvent }
    | { $case: "presenceEvent"; value: PresenceEvent }
    | { $case: "typingEvent"; value: TypingEvent }
    | { $case: "messageCreate"; value: MessageEvent }
    | { $case: "messageUpdate"; value: MessageEvent }
    | { $case: "messageDelete"; value: MessageDeleteEvent }
    | undefined;
}

/** Client -> Server 1XX */
export interface PresenceUpdateRequest {
  status: PresenceStatus;
  customText?: string | undefined;
}

export interface TypingRequest {
  channelId: string;
}

export interface VoiceChannelRequest {
  channelId: string;
  type: VoiceChannelEventType;
}

/** Server -> Client 2XX */
export interface VoiceChannelUserEvent {
  channelId: string;
  type: VoiceChannelEventType;
  userId: string;
}

export interface TypingEvent {
  userId: string;
  serverId?: string | undefined;
  channelId: string;
  expiresAt: number;
}

export interface UserPresence {
  userId: string;
  status: PresenceStatus;
  customText?: string | undefined;
}

export interface PresenceEvent {
  presences: UserPresence[];
}

export interface ChatMessage {
  id: string;
  channelId: string;
  userId?: string | undefined;
  content: string;
  createdAt: string;
  editedAt?: string | undefined;
}

export interface MessageEvent {
  message: ChatMessage | undefined;
  serverId?: string | undefined;
}

export interface MessageDeleteEvent {
  id: string;
  channelId: string;
  serverId?: string | undefined;
}

/** RTC 1X */
export interface RtcEvent {
  type: RtcEvent_RtcMessageType;
  target: string;
  sdp: string;
}

export enum RtcEvent_RtcMessageType {
  UNSPECIFIED = 0,
  Offer = 1,
  Answer = 2,
  PrAnswer = 3,
  Rollback = 4,
  UNRECOGNIZED = -1,
}

export interface RtcNewCandidate {
  target: string;
  candidate: RtcNewCandidate_IceCandidate | undefined;
}

export interface RtcNewCandidate_IceCandidate {
  candidate?: string | undefined;
  sdpMid?: string | undefined;
  sdpMLineIndex?: number | undefined;
  usernameFragment?: string | undefined;
}

function createBaseEnvelope(): Envelope {
  return { envelopeId: "", timestamp: 0, version: 0, payload: undefined };
}

export const Envelope: MessageFns<Envelope> = {
  encode(message: Envelope, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.envelopeId !== "") {
      writer.uint32(10).string(message.envelopeId);
    }
    if (message.timestamp !== 0) {
      writer.uint32(16).int64(message.timestamp);
    }
    if (message.version !== 0) {
      writer.uint32(24).uint32(message.version);
    }
    switch (message.payload?.$case) {
      case "rtc":
        RtcEvent.encode(message.payload.value, writer.uint32(82).fork()).join();
        break;
      case "rtcIce":
        RtcNewCandidate.encode(message.payload.value, writer.uint32(90).fork()).join();
        break;
      case "voiceChannelRequest":
        VoiceChannelRequest.encode(message.payload.value, writer.uint32(802).fork()).join();
        break;
      case "presenceEventRequest":
        PresenceUpdateRequest.encode(message.payload.value, writer.uint32(810).fork()).join();
        break;
      case "typingEventRequest":
        TypingRequest.encode(message.payload.value, writer.uint32(818).fork()).join();
        break;
      case "voiceChannelEvent":
        VoiceChannelUserEvent.encode(message.payload.value, writer.uint32(1602).fork()).join();
        break;
      case "presenceEvent":
        PresenceEvent.encode(message.payload.value, writer.uint32(1610).fork()).join();
        break;
      case "typingEvent":
        TypingEvent.encode(message.payload.value, writer.uint32(1618).fork()).join();
        break;
      case "messageCreate":
        MessageEvent.encode(message.payload.value, writer.uint32(1626).fork()).join();
        break;
      case "messageUpdate":
        MessageEvent.encode(message.payload.value, writer.uint32(1634).fork()).join();
        break;
      case "messageDelete":
        MessageDeleteEvent.encode(message.payload.value, writer.uint32(1642).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Envelope {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEnvelope();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.envelopeId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.version = reader.uint32();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.payload = { $case: "rtc", value: RtcEvent.decode(reader, reader.uint32()) };
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.payload = { $case: "rtcIce", value: RtcNewCandidate.decode(reader, reader.uint32()) };
          continue;
        }
        case 100: {
          if (tag !== 802) {
            break;
          }

          message.payload = {
            $case: "voiceChannelRequest",
            value: VoiceChannelRequest.decode(reader, reader.uint32()),
          };
          continue;
        }
        case 101: {
          if (tag !== 810) {
            break;
          }

          message.payload = {
            $case: "presenceEventRequest",
            value: PresenceUpdateRequest.decode(reader, reader.uint32()),
          };
          continue;
        }
        case 102: {
          if (tag !== 818) {
            break;
          }

          message.payload = { $case: "typingEventRequest", value: TypingRequest.decode(reader, reader.uint32()) };
          continue;
        }
        case 200: {
          if (tag !== 1602) {
            break;
          }

          message.payload = {
            $case: "voiceChannelEvent",
            value: VoiceChannelUserEvent.decode(reader, reader.uint32()),
          };
          continue;
        }
        case 201: {
          if (tag !== 1610) {
            break;
          }

          message.payload = { $case: "presenceEvent", value: PresenceEvent.decode(reader, reader.uint32()) };
          continue;
        }
        case 202: {
          if (tag !== 1618) {
            break;
          }

          message.payload = { $case: "typingEvent", value: TypingEvent.decode(reader, reader.uint32()) };
          continue;
        }
        case 203: {
          if (tag !== 1626) {
            break;
          }

          message.payload = { $case: "messageCreate", value: MessageEvent.decode(reader, reader.uint32()) };
          continue;
        }
        case 204: {
          if (tag !== 1634) {
            break;
          }

          message.payload = { $case: "messageUpdate", value: MessageEvent.decode(reader, reader.uint32()) };
          continue;
        }
        case 205: {
          if (tag !== 1642) {
            break;
          }

          message.payload = { $case: "messageDelete", value: MessageDeleteEvent.decode(reader, reader.uint32()) };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Envelope>, I>>(base?: I): Envelope {
    return Envelope.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Envelope>, I>>(object: I): Envelope {
    const message = createBaseEnvelope();
    message.envelopeId = object.envelopeId ?? "";
    message.timestamp = object.timestamp ?? 0;
    message.version = object.version ?? 0;
    switch (object.payload?.$case) {
      case "rtc": {
        if (object.payload?.value !== undefined && object.payload?.value !== null) {
          message.payload = { $case: "rtc", value: RtcEvent.fromPartial(object.payload.value) };
        }
        break;
      }
      case "rtcIce": {
        if (object.payload?.value !== undefined && object.payload?.value !== null) {
          message.payload = { $case: "rtcIce", value: RtcNewCandidate.fromPartial(object.payload.value) };
        }
        break;
      }
      case "voiceChannelRequest": {
        if (object.payload?.value !== undefined && object.payload?.value !== null) {
          message.payload = {
            $case: "voiceChannelRequest",
            value: VoiceChannelRequest.fromPartial(object.payload.value),
          };
        }
        break;
      }
      case "presenceEventRequest": {
        if (object.payload?.value !== undefined && object.payload?.value !== null) {
          message.payload = {
            $case: "presenceEventRequest",
            value: PresenceUpdateRequest.fromPartial(object.payload.value),
          };
        }
        break;
      }
      case "typingEventRequest": {
        if (object.payload?.value !== undefined && object.payload?.value !== null) {
          message.payload = { $case: "typingEventRequest", value: TypingRequest.fromPartial(object.payload.value) };
        }
        break;
      }
      case "voiceChannelEvent": {
        if (object.payload?.value !== undefined && object.payload?.value !== null) {
          message.payload = {
            $case: "voiceChannelEvent",
            value: VoiceChannelUserEvent.fromPartial(object.payload.value),
          };
        }
        break;
      }
      case "presenceEvent": {
        if (object.payload?.value !== undefined && object.payload?.value !== null) {
          message.payload = { $case: "presenceEvent", value: PresenceEvent.fromPartial(object.payload.value) };
        }
        break;
      }
      case "typingEvent": {
        if (object.payload?.value !== undefined && object.payload?.value !== null) {
          message.payload = { $case: "typingEvent", value: TypingEvent.fromPartial(object.payload.value) };
        }
        break;
      }
      case "messageCreate": {
        if (object.payload?.value !== undefined && object.payload?.value !== null) {
          message.payload = { $case: "messageCreate", value: MessageEvent.fromPartial(object.payload.value) };
        }
        break;
      }
      case "messageUpdate": {
        if (object.payload?.value !== undefined && object.payload?.value !== null) {
          message.payload = { $case: "messageUpdate", value: MessageEvent.fromPartial(object.payload.value) };
        }
        break;
      }
      case "messageDelete": {
        if (object.payload?.value !== undefined && object.payload?.value !== null) {
          message.payload = { $case: "messageDelete", value: MessageDeleteEvent.fromPartial(object.payload.value) };
        }
        break;
      }
    }
    return message;
  },
};

function createBasePresenceUpdateRequest(): PresenceUpdateRequest {
  return { status: 0, customText: undefined };
}

export const PresenceUpdateRequest: MessageFns<PresenceUpdateRequest> = {
  encode(message: PresenceUpdateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== 0) {
      writer.uint32(8).int32(message.status);
    }
    if (message.customText !== undefined) {
      writer.uint32(18).string(message.customText);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PresenceUpdateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePresenceUpdateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.customText = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<PresenceUpdateRequest>, I>>(base?: I): PresenceUpdateRequest {
    return PresenceUpdateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PresenceUpdateRequest>, I>>(object: I): PresenceUpdateRequest {
    const message = createBasePresenceUpdateRequest();
    message.status = object.status ?? 0;
    message.customText = object.customText ?? undefined;
    return message;
  },
};

function createBaseTypingRequest(): TypingRequest {
  return { channelId: "" };
}

export const TypingRequest: MessageFns<TypingRequest> = {
  encode(message: TypingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.channelId !== "") {
      writer.uint32(10).string(message.channelId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TypingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTypingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.channelId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<TypingRequest>, I>>(base?: I): TypingRequest {
    return TypingRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TypingRequest>, I>>(object: I): TypingRequest {
    const message = createBaseTypingRequest();
    message.channelId = object.channelId ?? "";
    return message;
  },
};

function createBaseVoiceChannelRequest(): VoiceChannelRequest {
  return { channelId: "", type: 0 };
}

export const VoiceChannelRequest: MessageFns<VoiceChannelRequest> = {
  encode(message: VoiceChannelRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.channelId !== "") {
      writer.uint32(10).string(message.channelId);
    }
    if (message.type !== 0) {
      writer.uint32(16).int32(message.type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VoiceChannelRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVoiceChannelRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.channelId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<VoiceChannelRequest>, I>>(base?: I): VoiceChannelRequest {
    return VoiceChannelRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VoiceChannelRequest>, I>>(object: I): VoiceChannelRequest {
    const message = createBaseVoiceChannelRequest();
    message.channelId = object.channelId ?? "";
    message.type = object.type ?? 0;
    return message;
  },
};

function createBaseVoiceChannelUserEvent(): VoiceChannelUserEvent {
  return { channelId: "", type: 0, userId: "" };
}

export const VoiceChannelUserEvent: MessageFns<VoiceChannelUserEvent> = {
  encode(message: VoiceChannelUserEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.channelId !== "") {
      writer.uint32(10).string(message.channelId);
    }
    if (message.type !== 0) {
      writer.uint32(16).int32(message.type);
    }
    if (message.userId !== "") {
      writer.uint32(26).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VoiceChannelUserEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVoiceChannelUserEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.channelId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<VoiceChannelUserEvent>, I>>(base?: I): VoiceChannelUserEvent {
    return VoiceChannelUserEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VoiceChannelUserEvent>, I>>(object: I): VoiceChannelUserEvent {
    const message = createBaseVoiceChannelUserEvent();
    message.channelId = object.channelId ?? "";
    message.type = object.type ?? 0;
    message.userId = object.userId ?? "";
    return message;
  },
};

function createBaseTypingEvent(): TypingEvent {
  return { userId: "", serverId: undefined, channelId: "", expiresAt: 0 };
}

export const TypingEvent: MessageFns<TypingEvent> = {
  encode(message: TypingEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.serverId !== undefined) {
      writer.uint32(18).string(message.serverId);
    }
    if (message.channelId !== "") {
      writer.uint32(26).string(message.channelId);
    }
    if (message.expiresAt !== 0) {
      writer.uint32(32).int64(message.expiresAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TypingEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTypingEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.serverId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.channelId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.expiresAt = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<TypingEvent>, I>>(base?: I): TypingEvent {
    return TypingEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TypingEvent>, I>>(object: I): TypingEvent {
    const message = createBaseTypingEvent();
    message.userId = object.userId ?? "";
    message.serverId = object.serverId ?? undefined;
    message.channelId = object.channelId ?? "";
    message.expiresAt = object.expiresAt ?? 0;
    return message;
  },
};

function createBaseUserPresence(): UserPresence {
  return { userId: "", status: 0, customText: undefined };
}

export const UserPresence: MessageFns<UserPresence> = {
  encode(message: UserPresence, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.status !== 0) {
      writer.uint32(16).int32(message.status);
    }
    if (message.customText !== undefined) {
      writer.uint32(26).string(message.customText);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserPresence {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserPresence();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.customText = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<UserPresence>, I>>(base?: I): UserPresence {
    return UserPresence.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserPresence>, I>>(object: I): UserPresence {
    const message = createBaseUserPresence();
    message.userId = object.userId ?? "";
    message.status = object.status ?? 0;
    message.customText = object.customText ?? undefined;
    return message;
  },
};

function createBasePresenceEvent(): PresenceEvent {
  return { presences: [] };
}

export const PresenceEvent: MessageFns<PresenceEvent> = {
  encode(message: PresenceEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.presences) {
      UserPresence.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PresenceEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePresenceEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.presences.push(UserPresence.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<PresenceEvent>, I>>(base?: I): PresenceEvent {
    return PresenceEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PresenceEvent>, I>>(object: I): PresenceEvent {
    const message = createBasePresenceEvent();
    message.presences = object.presences?.map((e) => UserPresence.fromPartial(e)) || [];
    return message;
  },
};

function createBaseChatMessage(): ChatMessage {
  return { id: "", channelId: "", userId: undefined, content: "", createdAt: "", editedAt: undefined };
}

export const ChatMessage: MessageFns<ChatMessage> = {
  encode(message: ChatMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.channelId !== "") {
      writer.uint32(18).string(message.channelId);
    }
    if (message.userId !== undefined) {
      writer.uint32(26).string(message.userId);
    }
    if (message.content !== "") {
      writer.uint32(34).string(message.content);
    }
    if (message.createdAt !== "") {
      writer.uint32(42).string(message.createdAt);
    }
    if (message.editedAt !== undefined) {
      writer.uint32(50).string(message.editedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChatMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChatMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.channelId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.editedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ChatMessage>, I>>(base?: I): ChatMessage {
    return ChatMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChatMessage>, I>>(object: I): ChatMessage {
    const message = createBaseChatMessage();
    message.id = object.id ?? "";
    message.channelId = object.channelId ?? "";
    message.userId = object.userId ?? undefined;
    message.content = object.content ?? "";
    message.createdAt = object.createdAt ?? "";
    message.editedAt = object.editedAt ?? undefined;
    return message;
  },
};

function createBaseMessageEvent(): MessageEvent {
  return { message: undefined, serverId: undefined };
}

export const MessageEvent: MessageFns<MessageEvent> = {
  encode(message: MessageEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== undefined) {
      ChatMessage.encode(message.message, writer.uint32(10).fork()).join();
    }
    if (message.serverId !== undefined) {
      writer.uint32(18).string(message.serverId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MessageEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessageEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = ChatMessage.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.serverId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<MessageEvent>, I>>(base?: I): MessageEvent {
    return MessageEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MessageEvent>, I>>(object: I): MessageEvent {
    const message = createBaseMessageEvent();
    message.message = (object.message !== undefined && object.message !== null)
      ? ChatMessage.fromPartial(object.message)
      : undefined;
    message.serverId = object.serverId ?? undefined;
    return message;
  },
};

function createBaseMessageDeleteEvent(): MessageDeleteEvent {
  return { id: "", channelId: "", serverId: undefined };
}

export const MessageDeleteEvent: MessageFns<MessageDeleteEvent> = {
  encode(message: MessageDeleteEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.channelId !== "") {
      writer.uint32(18).string(message.channelId);
    }
    if (message.serverId !== undefined) {
      writer.uint32(26).string(message.serverId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MessageDeleteEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessageDeleteEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.channelId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.serverId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<MessageDeleteEvent>, I>>(base?: I): MessageDeleteEvent {
    return MessageDeleteEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MessageDeleteEvent>, I>>(object: I): MessageDeleteEvent {
    const message = createBaseMessageDeleteEvent();
    message.id = object.id ?? "";
    message.channelId = object.channelId ?? "";
    message.serverId = object.serverId ?? undefined;
    return message;
  },
};

function createBaseRtcEvent(): RtcEvent {
  return { type: 0, target: "", sdp: "" };
}

export const RtcEvent: MessageFns<RtcEvent> = {
  encode(message: RtcEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.target !== "") {
      writer.uint32(18).string(message.target);
    }
    if (message.sdp !== "") {
      writer.uint32(26).string(message.sdp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RtcEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRtcEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.target = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.sdp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RtcEvent>, I>>(base?: I): RtcEvent {
    return RtcEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RtcEvent>, I>>(object: I): RtcEvent {
    const message = createBaseRtcEvent();
    message.type = object.type ?? 0;
    message.target = object.target ?? "";
    message.sdp = object.sdp ?? "";
    return message;
  },
};

function createBaseRtcNewCandidate(): RtcNewCandidate {
  return { target: "", candidate: undefined };
}

export const RtcNewCandidate: MessageFns<RtcNewCandidate> = {
  encode(message: RtcNewCandidate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.target !== "") {
      writer.uint32(10).string(message.target);
    }
    if (message.candidate !== undefined) {
      RtcNewCandidate_IceCandidate.encode(message.candidate, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RtcNewCandidate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRtcNewCandidate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.target = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.candidate = RtcNewCandidate_IceCandidate.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RtcNewCandidate>, I>>(base?: I): RtcNewCandidate {
    return RtcNewCandidate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RtcNewCandidate>, I>>(object: I): RtcNewCandidate {
    const message = createBaseRtcNewCandidate();
    message.target = object.target ?? "";
    message.candidate = (object.candidate !== undefined && object.candidate !== null)
      ? RtcNewCandidate_IceCandidate.fromPartial(object.candidate)
      : undefined;
    return message;
  },
};

function createBaseRtcNewCandidate_IceCandidate(): RtcNewCandidate_IceCandidate {
  return { candidate: undefined, sdpMid: undefined, sdpMLineIndex: undefined, usernameFragment: undefined };
}

export const RtcNewCandidate_IceCandidate: MessageFns<RtcNewCandidate_IceCandidate> = {
  encode(message: RtcNewCandidate_IceCandidate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.candidate !== undefined) {
      writer.uint32(10).string(message.candidate);
    }
    if (message.sdpMid !== undefined) {
      writer.uint32(18).string(message.sdpMid);
    }
    if (message.sdpMLineIndex !== undefined) {
      writer.uint32(24).int64(message.sdpMLineIndex);
    }
    if (message.usernameFragment !== undefined) {
      writer.uint32(34).string(message.usernameFragment);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RtcNewCandidate_IceCandidate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRtcNewCandidate_IceCandidate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.candidate = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sdpMid = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.sdpMLineIndex = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.usernameFragment = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RtcNewCandidate_IceCandidate>, I>>(base?: I): RtcNewCandidate_IceCandidate {
    return RtcNewCandidate_IceCandidate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RtcNewCandidate_IceCandidate>, I>>(object: I): RtcNewCandidate_IceCandidate {
    const message = createBaseRtcNewCandidate_IceCandidate();
    message.candidate = object.candidate ?? undefined;
    message.sdpMid = object.sdpMid ?? undefined;
    message.sdpMLineIndex = object.sdpMLineIndex ?? undefined;
    message.usernameFragment = object.usernameFragment ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string; value: unknown } ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
