// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v3.21.12
// source: hermes.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "hermes";

/** Client -> Server 1XX */
export enum VoiceChannelEventType {
  Join = 0,
  Leave = 1,
  UNRECOGNIZED = -1,
}

export interface Envelope {
  messageId: string;
  timestamp: number;
  version: number;
  /** RTC 1X */
  rtc?: RtcEvent | undefined;
  rtcIce?:
    | RtcNewCandidate
    | undefined;
  /** Client -> Server 1XX */
  voiceChannelRequest?:
    | VoiceChannelRequest
    | undefined;
  /** Server -> Client 2XX */
  voiceChannelEvent?: VoiceChannelUserEvent | undefined;
}

export interface VoiceChannelUserEvent {
  channelId: string;
  type: VoiceChannelEventType;
  userId: string;
}

/** Server -> Client 2XX */
export interface VoiceChannelRequest {
  channelId: string;
  type: VoiceChannelEventType;
}

/** RTC 1X */
export interface RtcEvent {
  type: RtcEvent_RtcMessageType;
  target: string;
  sdp: string;
}

export enum RtcEvent_RtcMessageType {
  Offer = 0,
  Answer = 1,
  PrAnswer = 2,
  Rollback = 3,
  UNRECOGNIZED = -1,
}

export interface RtcNewCandidate {
  target: string;
  candidate: RtcNewCandidate_IceCandidate | undefined;
}

export interface RtcNewCandidate_IceCandidate {
  candidate?: string | undefined;
  sdpMid?: string | undefined;
  sdpMLineIndex?: number | undefined;
  usernameFragment?: string | undefined;
}

function createBaseEnvelope(): Envelope {
  return {
    messageId: "",
    timestamp: 0,
    version: 0,
    rtc: undefined,
    rtcIce: undefined,
    voiceChannelRequest: undefined,
    voiceChannelEvent: undefined,
  };
}

export const Envelope: MessageFns<Envelope> = {
  encode(message: Envelope, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.messageId !== "") {
      writer.uint32(10).string(message.messageId);
    }
    if (message.timestamp !== 0) {
      writer.uint32(16).int64(message.timestamp);
    }
    if (message.version !== 0) {
      writer.uint32(24).uint32(message.version);
    }
    if (message.rtc !== undefined) {
      RtcEvent.encode(message.rtc, writer.uint32(82).fork()).join();
    }
    if (message.rtcIce !== undefined) {
      RtcNewCandidate.encode(message.rtcIce, writer.uint32(90).fork()).join();
    }
    if (message.voiceChannelRequest !== undefined) {
      VoiceChannelRequest.encode(message.voiceChannelRequest, writer.uint32(802).fork()).join();
    }
    if (message.voiceChannelEvent !== undefined) {
      VoiceChannelUserEvent.encode(message.voiceChannelEvent, writer.uint32(1602).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Envelope {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEnvelope();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.messageId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.version = reader.uint32();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.rtc = RtcEvent.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.rtcIce = RtcNewCandidate.decode(reader, reader.uint32());
          continue;
        }
        case 100: {
          if (tag !== 802) {
            break;
          }

          message.voiceChannelRequest = VoiceChannelRequest.decode(reader, reader.uint32());
          continue;
        }
        case 200: {
          if (tag !== 1602) {
            break;
          }

          message.voiceChannelEvent = VoiceChannelUserEvent.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Envelope>, I>>(base?: I): Envelope {
    return Envelope.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Envelope>, I>>(object: I): Envelope {
    const message = createBaseEnvelope();
    message.messageId = object.messageId ?? "";
    message.timestamp = object.timestamp ?? 0;
    message.version = object.version ?? 0;
    message.rtc = (object.rtc !== undefined && object.rtc !== null) ? RtcEvent.fromPartial(object.rtc) : undefined;
    message.rtcIce = (object.rtcIce !== undefined && object.rtcIce !== null)
      ? RtcNewCandidate.fromPartial(object.rtcIce)
      : undefined;
    message.voiceChannelRequest = (object.voiceChannelRequest !== undefined && object.voiceChannelRequest !== null)
      ? VoiceChannelRequest.fromPartial(object.voiceChannelRequest)
      : undefined;
    message.voiceChannelEvent = (object.voiceChannelEvent !== undefined && object.voiceChannelEvent !== null)
      ? VoiceChannelUserEvent.fromPartial(object.voiceChannelEvent)
      : undefined;
    return message;
  },
};

function createBaseVoiceChannelUserEvent(): VoiceChannelUserEvent {
  return { channelId: "", type: 0, userId: "" };
}

export const VoiceChannelUserEvent: MessageFns<VoiceChannelUserEvent> = {
  encode(message: VoiceChannelUserEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.channelId !== "") {
      writer.uint32(10).string(message.channelId);
    }
    if (message.type !== 0) {
      writer.uint32(16).int32(message.type);
    }
    if (message.userId !== "") {
      writer.uint32(26).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VoiceChannelUserEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVoiceChannelUserEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.channelId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<VoiceChannelUserEvent>, I>>(base?: I): VoiceChannelUserEvent {
    return VoiceChannelUserEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VoiceChannelUserEvent>, I>>(object: I): VoiceChannelUserEvent {
    const message = createBaseVoiceChannelUserEvent();
    message.channelId = object.channelId ?? "";
    message.type = object.type ?? 0;
    message.userId = object.userId ?? "";
    return message;
  },
};

function createBaseVoiceChannelRequest(): VoiceChannelRequest {
  return { channelId: "", type: 0 };
}

export const VoiceChannelRequest: MessageFns<VoiceChannelRequest> = {
  encode(message: VoiceChannelRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.channelId !== "") {
      writer.uint32(10).string(message.channelId);
    }
    if (message.type !== 0) {
      writer.uint32(16).int32(message.type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VoiceChannelRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVoiceChannelRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.channelId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<VoiceChannelRequest>, I>>(base?: I): VoiceChannelRequest {
    return VoiceChannelRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VoiceChannelRequest>, I>>(object: I): VoiceChannelRequest {
    const message = createBaseVoiceChannelRequest();
    message.channelId = object.channelId ?? "";
    message.type = object.type ?? 0;
    return message;
  },
};

function createBaseRtcEvent(): RtcEvent {
  return { type: 0, target: "", sdp: "" };
}

export const RtcEvent: MessageFns<RtcEvent> = {
  encode(message: RtcEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.target !== "") {
      writer.uint32(18).string(message.target);
    }
    if (message.sdp !== "") {
      writer.uint32(26).string(message.sdp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RtcEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRtcEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.target = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.sdp = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RtcEvent>, I>>(base?: I): RtcEvent {
    return RtcEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RtcEvent>, I>>(object: I): RtcEvent {
    const message = createBaseRtcEvent();
    message.type = object.type ?? 0;
    message.target = object.target ?? "";
    message.sdp = object.sdp ?? "";
    return message;
  },
};

function createBaseRtcNewCandidate(): RtcNewCandidate {
  return { target: "", candidate: undefined };
}

export const RtcNewCandidate: MessageFns<RtcNewCandidate> = {
  encode(message: RtcNewCandidate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.target !== "") {
      writer.uint32(10).string(message.target);
    }
    if (message.candidate !== undefined) {
      RtcNewCandidate_IceCandidate.encode(message.candidate, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RtcNewCandidate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRtcNewCandidate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.target = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.candidate = RtcNewCandidate_IceCandidate.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RtcNewCandidate>, I>>(base?: I): RtcNewCandidate {
    return RtcNewCandidate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RtcNewCandidate>, I>>(object: I): RtcNewCandidate {
    const message = createBaseRtcNewCandidate();
    message.target = object.target ?? "";
    message.candidate = (object.candidate !== undefined && object.candidate !== null)
      ? RtcNewCandidate_IceCandidate.fromPartial(object.candidate)
      : undefined;
    return message;
  },
};

function createBaseRtcNewCandidate_IceCandidate(): RtcNewCandidate_IceCandidate {
  return { candidate: undefined, sdpMid: undefined, sdpMLineIndex: undefined, usernameFragment: undefined };
}

export const RtcNewCandidate_IceCandidate: MessageFns<RtcNewCandidate_IceCandidate> = {
  encode(message: RtcNewCandidate_IceCandidate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.candidate !== undefined) {
      writer.uint32(10).string(message.candidate);
    }
    if (message.sdpMid !== undefined) {
      writer.uint32(18).string(message.sdpMid);
    }
    if (message.sdpMLineIndex !== undefined) {
      writer.uint32(24).int64(message.sdpMLineIndex);
    }
    if (message.usernameFragment !== undefined) {
      writer.uint32(34).string(message.usernameFragment);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RtcNewCandidate_IceCandidate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRtcNewCandidate_IceCandidate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.candidate = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sdpMid = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.sdpMLineIndex = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.usernameFragment = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RtcNewCandidate_IceCandidate>, I>>(base?: I): RtcNewCandidate_IceCandidate {
    return RtcNewCandidate_IceCandidate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RtcNewCandidate_IceCandidate>, I>>(object: I): RtcNewCandidate_IceCandidate {
    const message = createBaseRtcNewCandidate_IceCandidate();
    message.candidate = object.candidate ?? undefined;
    message.sdpMid = object.sdpMid ?? undefined;
    message.sdpMLineIndex = object.sdpMLineIndex ?? undefined;
    message.usernameFragment = object.usernameFragment ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
