openapi: 3.1.0
info:
  title: hermes-server
  description: Hermes server
  license:
    name: ''
  version: 0.1.0
paths:
  /api/v1/server/{server}:
    get:
      tags:
      - server
      description: fetch a server
      operationId: get_server
      parameters:
      - name: server
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: single server info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Server'
    post:
      tags:
      - server
      description: create a server
      operationId: post_server
      responses: {}
    delete:
      tags:
      - server
      description: delete a server
      operationId: delete_server
      responses: {}
    patch:
      tags:
      - server
      description: update a server
      operationId: patch_server
      responses: {}
components:
  schemas:
    Server:
      type: object
      required:
      - id
      - name
      - owner_id
      - created_at
      properties:
        created_at:
          type: string
          format: date-time
        icon:
          type:
          - string
          - 'null'
        id:
          type: string
          format: uuid
        name:
          type: string
        owner_id:
          type: string
          format: uuid
